export const BASE_URL = import.meta.env.VITE_BASE_URL;

export const POST_ISSUE = "POST_ISSUE";

export const GET_ISSUES = "GET_ISSUES";

export const GET_All_ISSUES = "GET_All_ISSUES";
export const GET_TOP = "GET_TOP";
export const GET_APPROVE = "GET_APPROVE";
export const GET_PRIORIZADOSXAREA_ISSUES = "GET_PRIORIZADOSXAREA_ISSUES";

export const GET_ISSUETYPE = 'GET_ISSUETYPE'

export const GET_PROJECTS = "GET_PROJECTS";

export const GET_BOARD = "GET_BOARD";

export const GET_TRANSITIONS = "GET_TRANSITIONS";

export const POST_USER = "POST_USER";

export const GET_COMMENT_ISSUES = "GET_COMMENT_ISSUES";

export const CLEAR_COMMENT_STATE = "CLEAR_COMMENT_STATE";

export const NEW_COMMENT = "NEW_COMMENT"

export const EDIT_DESC = 'EDIT_DESC'

export const SET_USER_DATA = 'SET_USER_DATA'

export const GET_WORKLOG = 'GET_WORKLOG'

export const GET_ISSUE_BY_USER = 'GET_ISSUE_BY_USER'

export const GET_ISSUE_BY_KEY = 'GET_ISSUE_BY_KEY'

export const CLEAR_ISSUE_BY_KEY = 'CLEAR_ISSUE_BY_KEY'

export const ERROR_GET_ISSUE_BY_KEY = 'ERROR_GET_ISSUE_BY_KEY'

export const GET_USERS_IT = 'GET_USERS_IT'
export const ERROR_GET_USERS_IT = 'ERROR_GET_USERS_IT'

export const GET_ISSUES_IN_PROCESS = 'GET_ISSUES_IN_PROCESS'
export const ERROR_GET_ISSUES_IN_PROCESS = 'ERROR_GET_ISSUES_IN_PROCESS'